/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ROBOT_H__
#define __ROBOT_H__

#ifdef __cplusplus
extern "C"
{
#endif


/* Version system */
#define ROBOT_NAME "breast-elastography-robot"
#define ROBOT_VERSION 1.0

/* Define standard libraries used by robot */
#include "stm32f1xx_hal.h"
#include "stdlib.h"
#include "stdbool.h"
#include "ctype.h"
#include "string.h"
#include "stdint.h"
#include "inttypes.h"
#include "math.h"


/* Define the system include files. NOTE: Do not alter organization */
/* Generated by CubeMX */
#include "gpio.h"
#include "tim.h"

/* User written */
#include "stepper.h"

#ifdef __cplusplus
}
#endif

#endif /* __ROBOT_H__ */
